name: meta_weather_api
description: A Dart Api Client for MetaWeather API.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.4
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.5
  json_serializable: ^6.1.1
  mocktail: ^0.1.4
  test: ^1.19.5
  very_good_analysis: ^2.4.0