name: meta_weather_api
description: A Dart Api Client for MetaWeather API.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.3
  json_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^2.1.1
  json_serializable: ^5.0.0
  mocktail: ^0.1.4
  test: ^1.17.10
  very_good_analysis: ^2.3.0