name: weather
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  google_fonts: ^2.1.0
  hydrated_bloc: ^8.0.0
  intl: ^0.17.0
  json_annotation: ^4.0.0
  path_provider: ^2.0.6
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  bloc_test: ^9.0.1
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  json_serializable: ^5.0.0
  mocktail: ^0.2.0
  test: ^1.16.8
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true
